// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3uuiwbCpxJylC4Tg7Ovn4BHlyrELoQQ',
    appId: '1:29248417073:web:3b26f12fef86d984b2d410',
    messagingSenderId: '29248417073',
    projectId: 'genaiignite-01',
    authDomain: 'genaiignite-01.firebaseapp.com',
    storageBucket: 'genaiignite-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq3v3aWp_1Ej3CQVBoEcbQl-ywaPbHzpc',
    appId: '1:29248417073:android:98fd33fd8cf9f365b2d410',
    messagingSenderId: '29248417073',
    projectId: 'genaiignite-01',
    storageBucket: 'genaiignite-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnF6VjGXX7054Dmu9-8YbOmwocfIZJ-Zo',
    appId: '1:29248417073:ios:add8ce6256aca2f3b2d410',
    messagingSenderId: '29248417073',
    projectId: 'genaiignite-01',
    storageBucket: 'genaiignite-01.firebasestorage.app',
    iosBundleId: 'com.example.aignite2025Oops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnF6VjGXX7054Dmu9-8YbOmwocfIZJ-Zo',
    appId: '1:29248417073:ios:add8ce6256aca2f3b2d410',
    messagingSenderId: '29248417073',
    projectId: 'genaiignite-01',
    storageBucket: 'genaiignite-01.firebasestorage.app',
    iosBundleId: 'com.example.aignite2025Oops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-3uuiwbCpxJylC4Tg7Ovn4BHlyrELoQQ',
    appId: '1:29248417073:web:015d2d0a3e056fbab2d410',
    messagingSenderId: '29248417073',
    projectId: 'genaiignite-01',
    authDomain: 'genaiignite-01.firebaseapp.com',
    storageBucket: 'genaiignite-01.firebasestorage.app',
  );
}
